module: Core
output: docs/Core

clean: true
author: Zewo
author_url: http://zewo.io
github_url: https://github.com/Zewo/Zewo
swift_version: 5.1

custom_categories:
  - name: Stream
    children:
    - ReadableStream
    - WritableStream
    - DuplexStream

  - name: Media Type
    children:
    - MediaType

  - name: Content
    children:
    - Content
    - NoContent
    - ContentInitializable
    - ContentRepresentable
    - ContentConvertible
    - ContentParser
    - ContentSerializer
    - ContentType

  - name: JSON
    children:
    - JSONParser
    - JSONParserError
    - JSONSerializer
    - JSONSerializerError

  - name: URI
    children:
    - URI
  
  - name: Logger
    children:
    - Logger
    - LogAppender
    - StandardOutputAppender