name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
       os: [macos-latest, ubuntu-16.04, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: eval "$(curl -sL http://sh.zewo.io/install-zewo.sh)"
    - name: Build
      run: eval "$(curl -sL http://sh.zewo.io/build.sh)"
    - name: Coverage
      uses: paambaati/codeclimate-action@v2.5.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.codeClimateTestReporterId }}
      with:
        coverageCommand: eval "$(curl -sL http://sh.zewo.io/install-zewo.sh)"
        debug: true
