name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: eval "$(curl -sL http://sh.zewo.io/install-zewo.sh)"
    - name: Build
      run: eval "$(curl -sL http://sh.zewo.io/build.sh)"
